
#pragma once

#define ACCES_PCI_VEN_ID 0x494f

//ISR contexts: For cards that have device or functionality specific
//data that needs to be accessed in the ISR

union accesio_pci_isr_context
{
  struct dma_isr_context
  {
      dma_addr_t dma_addr;
      void *dma_virt_addr;
      int dma_last_buffer; //last dma started to fill
      int dma_first_valid; //first buffer containing valid data
      int dma_num_slots;
      size_t dma_slot_size;
      int dma_data_discarded;
      spinlock_t dma_data_lock;
  }dma_context;
};

//Function to be called to perform actions that vary by card. Effort should
//be made to reuse functions for cards in the same family or with identical
//operations
typedef void (*register_operation_t) (void *);

//Do we want an enum for which struct to use in ISR context?
struct accesio_pci_device_descriptor
{
  __u32                         pid;
  const char                    *name;
  irq_handler_t                 isr;
  register_operation_t          init;  //called during probe
  register_operation_t          test_latched; //does card have IRQ pending? Is this still needed now that isr is function pointer?
  register_operation_t          enable; //enable IRQs
  register_operation_t          disable; //disable IRQs
  register_operation_t          clear; //clear IRQ. TODO: May not be needed since using isr_handler above now.
  bool                          has_dma;
};



void enable_pci_style_1 (void *context);
void disable_pci_style_1 (void *context);
irqreturn_t interrupt_pci_style_1 (int irq, void *context);
void enable_pci_style_2 (void*context);
void disable_pci_style_2 (void *context);
irqreturn_t interrupt_pci_style_2 (int irq, void *context);
void enable_pci_style_3(void * context);
void disable_pci_style_3 (void *context);
irqreturn_t interrupt_pci_style_3 (int irq, void *context);
void enable_pci_style_4 (void * context);
void disable_pci_style_4 (void *context);
irqreturn_t interrupt_pci_style_4 (int irq, void *context);
void enable_pci_style_5 (void * context);
void disable_pci_style_5 (void *context);
irqreturn_t interrupt_pci_style_5 (int irq, void *context);
void enable_pci_style_6 (void * context);
void disable_pci_style_6 (void *context);
irqreturn_t interrupt_pci_style_6 (int irq, void *context);
void enable_pci_style_7 (void * context);
#define disable_pci_style_7 disable_pci_style_6
irqreturn_t interrupt_pci_style_7 (int irq, void *context);
void enable_pci_style_8 (void * context);
void disable_pci_style_8 (void *context);
irqreturn_t interrupt_pci_style_8 (int irq, void *context);
void enable_pci_style_9 (void * context);
void disable_pci_style_9 (void *context);
irqreturn_t interrupt_pci_style_9 (int irq, void *context);
void enable_pci_style_10 (void * context);
void disable_pci_style_10 (void *context);
irqreturn_t interrupt_pci_style_10 (int irq, void *context);
//PCI_11 style undefined in old header. ;
//TODO: Find manuals for PCI style 11;
// struct aio_irq_descriptor PCI_11_STYLE = /* S4C&04|E<00|8#6|E<FF	 */;
void enable_pci_style_12 (void * context);
void disable_pci_style_12 (void *context);
irqreturn_t interrupt_pci_style_12 (int irq, void *context);
void enable_pci_style_13 (void * context);
void disable_pci_style_13 (void *context);
irqreturn_t interrupt_pci_style_13 (int irq, void *context);
void enable_pcie_style_1 (void * context);
void disable_pcie_style_1 (void *context);
irqreturn_t interrupt_pcie_style_1 (int irq, void *context);
void enable_pcie_style_2 (void * context);
void disable_pcie_style_2 (void *context);
irqreturn_t interrupt_pcie_style_2 (int irq, void *context);
void enable_pcie_style_3 (void * context);
void disable_pcie_style_3 (void *context);
irqreturn_t interrupt_pcie_style_3 (int irq, void *context);
void enable_pcie_style_4 (void * context);
void disable_pcie_style_4 (void *context);
irqreturn_t interrupt_pcie_style_4 (int irq, void *context);
#define enable_pcie_style_5 enable_pcie_style_4
void disable_pcie_style_5 (void *context);
#define interrupt_pcie_style_5 interrupt_pcie_style_4
void enable_pcie_style_6 (void * context);
void disable_pcie_style_6 (void *context);
irqreturn_t interrupt_pcie_style_6 (int irq, void *context);
void enable_pcie_style_7 (void * context);
#define disable_pcie_style_7 disable_pcie_style_6
irqreturn_t interrupt_pcie_style_7 (int irq, void *context);
void enable_pcie_style_8 (void * context);
void disable_pcie_style_8 (void *context);
irqreturn_t interrupt_pcie_style_8 (int irq, void *context);
void enable_adio16f_style (void *context);
void disable_adio16f_style (void *context);
irqreturn_t interrupt_adio16f_style (int irq, void *context);

static struct accesio_pci_device_descriptor accesio_pci_device_descriptors[] =
{
  {
    //.pciDevId = 0x0100, .Model = "mPCIe-DIO-24S", .IRQ = &PCIE_2_STYLE,
    .pid= 0x0100,
    .name = "mPCIe-DIO-24S",
    .isr = interrupt_pcie_style_2,
    .init = NULL,
    .enable = enable_pcie_style_2,
    .disable = disable_pcie_style_2,
    .clear = NULL,
  },
  {
    //pciDevId = 0x0101, .Model = "mPCIe-IDIO-8", .IRQ = &PCIE_2_STYLE,
    .pid= 0x0101,
    .name = "mPCIe-IDIO-8",
    .isr = interrupt_pcie_style_2,
    .init = NULL,
    .enable = enable_pcie_style_2,
    .disable = disable_pcie_style_2,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0102, .Model = "mPCIe-IIRO-8", .IRQ = &PCIE_2_STYLE,
    .pid= 0x0102,
    .name = "mPCIe-IIRO-8",
    .isr = interrupt_pcie_style_2,
    .init = NULL,
    .enable = enable_pcie_style_2,
    .disable = disable_pcie_style_2,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0103, .Model = "mPCIe-IDIO-4", .IRQ = &PCIE_2_STYLE,
    .pid= 0x0103,
    .name = "mPCIe-IDIO-4",
    .isr = interrupt_pcie_style_2,
    .init = NULL,
    .enable = enable_pcie_style_2,
    .disable = disable_pcie_style_2,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0104, .Model = "mPCIe-IIRO-4", .IRQ = &PCIE_2_STYLE,
    .pid= 0x0104,
    .name = "mPCIe-IIRO-4",
    .isr = interrupt_pcie_style_2,
    .init = NULL,
    .enable = enable_pcie_style_2,
    .disable = disable_pcie_style_2,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0105, .Model = "mPCIe-IDO-8", .IRQ = &PCIE_2_STYLE,
    .pid= 0x0105,
    .name = "mPCIe-IDO-8",
    .isr = interrupt_pcie_style_2,
    .init = NULL,
    .enable = enable_pcie_style_2,
    .disable = disable_pcie_style_2,
    .clear = NULL,
  },
  {
        //.pciDevId = 0x0106, .Model = "mPCIe-RO-8", .IRQ = &PCIE_2_STYLE,
    .pid= 0x0106,
    .name = "mPCIe-RO-8",
    .isr = interrupt_pcie_style_2,
    .init = NULL,
    .enable = enable_pcie_style_2,
    .disable = disable_pcie_style_2,
    .clear = NULL,
  },
  {
   //.pciDevId = 0x0107, .Model = "mPCIe-II-16", .IRQ = &PCIE_2_STYLE,
    .pid= 0x0107,
    .name = "mPCIe-II-16",
    .isr = interrupt_pcie_style_2,
   .init = NULL,
    .enable = enable_pcie_style_2,
    .disable = disable_pcie_style_2,
   .clear = NULL,
  },
  {
   //.pciDevId = 0x0108, .Model = "mPCIe-II-8", .IRQ = &PCIE_2_STYLE,
    .pid= 0x0108,
    .name = "mPCIe-II-8",
    .isr = interrupt_pcie_style_2,
   .init = NULL,
    .enable = enable_pcie_style_2,
    .disable = disable_pcie_style_2,
   .clear = NULL,
  },
  {
    //.pciDevId = 0x0109, .Model = "mPCIe-II-4", .IRQ = &PCIE_2_STYLE,
    .pid= 0x0109,
    .name = "mPCIe-II-4",
    .isr = interrupt_pcie_style_2,
   .init = NULL,
    .enable = enable_pcie_style_2,
    .disable = disable_pcie_style_2,
   .clear = NULL,
  },
  {
    //.pciDevId = 0x010A, .Model = "mPCIe-QUAD-4", .IRQ = &PCIE_2_STYLE,
    .pid= 0x010A,
    .name = "mPCIe-QUAD-4",
    .isr = interrupt_pcie_style_2,
    .init = NULL,
    .enable = enable_pcie_style_2,
    .disable = disable_pcie_style_2,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x010B, .Model = "mPCIe-QUAD-8", .IRQ = &PCIE_2_STYLE,
    .pid= 0x010B,
    .name = "mPCIe-QUAD-8",
    .isr = interrupt_pcie_style_2,
    .init = NULL,
    .enable = enable_pcie_style_2,
    .disable = disable_pcie_style_2,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x010C, .Model = "mod-TBD", .IRQ = &NYI,
    .pid= 0x010C,
    .name = "mod-TBD",
    .isr = NULL,
    .init = NULL,
    .enable = NULL,
    .disable = NULL,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x010D, .Model = "mod-TBD", .IRQ = &NYI,
    .pid= 0x010D,
    .name = "mod-TBD",
    .isr = NULL,
    .init = NULL,
    .enable = NULL,
    .disable = NULL,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x010E, .Model = "mod-TBD", .IRQ = &NYI,
    .pid= 0x010E,
    .name = "mod-TBD",
    .isr = NULL,
    .init = NULL,
    .enable = NULL,
    .disable = NULL,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x010F, .Model = "mod-TBD", .IRQ = &NYI,
    .pid= 0x010F,
    .name = "mod-TBD",
    .isr = NULL,
    .init = NULL,
    .enable = NULL,
    .disable = NULL,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0508, .Model = "PCI-IDO-16A", .IRQ = &PCI_NO_IRQ_STYLE,
    .pid= 0x0508,
    .name = "PCI-IDO-16A",
    .isr = NULL,
    .init = NULL,
    .enable = NULL,
    .disable = NULL,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0518, .Model = "PCI-IDO-32A", .IRQ = &PCI_NO_IRQ_STYLE,
    .pid= 0x0518,
    .name = "PCI-IDO-32A",
    .isr = NULL,
    .init = NULL,
    .enable = NULL,
    .disable = NULL,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0520, .Model = "PCI-IDO-48", .IRQ = &PCI_NO_IRQ_STYLE,
    .pid= 0x0520,
    .name = "PCI-IDO-48",
    .isr = NULL,
    .init = NULL,
    .enable = NULL,
    .disable = NULL,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0521, .Model = "PCI-IDO-48A", .IRQ = &PCI_NO_IRQ_STYLE,
    .pid= 0x0521,
    .name = "PCI-IDO-48A",
    .isr = NULL,
    .init = NULL,
    .enable = NULL,
    .disable = NULL,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0703, .Model = "PCIe-RO-4", .IRQ = &PCIE_3_STYLE,
    .pid= 0x0703,
    .name = "PCIe-RO-4",
    .isr = interrupt_pcie_style_3,
    .init = NULL,
    .enable = enable_pcie_style_3,
    .disable = disable_pcie_style_3,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x07C0, .Model = "PCIe-IDO-12", .IRQ = &NYI,
    .pid= 0x07C0,
    .name = "PCIe-IDO-12",
    .isr = NULL,
    .init = NULL,
    .enable = NULL,
    .disable = NULL,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x07D0, .Model = "PCIe-IDO-24", .IRQ = &PCIE_6_STYLE,
    .pid= 0x07D0,
    .name = "PCIe-IDO-24",
    .isr = interrupt_pcie_style_6,
    .init = NULL,
    .enable = enable_pcie_style_6,
    .disable = disable_pcie_style_6,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0920, .Model = "PCI-IDI-48", .IRQ = &PCI_5_STYLE,
    .pid= 0x0920,
    .name = "PCI-IDI-48",
    .isr = interrupt_pci_style_5,
    .init = NULL,
    .enable = enable_pci_style_5,
    .disable = disable_pci_style_5,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0BC0, .Model = "PCIe-IDI-12A", .IRQ = &NYI,
    .pid= 0x0BC0,
    .name = "PCIe-IDI-12A",
    .isr = NULL,
    .init = NULL,
    .enable = NULL,
    .disable = NULL,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0BC1, .Model = "PCIe-IDI-12B", .IRQ = &NYI,
    .pid= 0x0BC1,
    .name = "PCIe-IDI-12B",
    .isr = NULL,
    .init = NULL,
    .enable = NULL,
    .disable = NULL,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0BD0, .Model = "PCIe-IDI-24", .IRQ = &PCIE_6_STYLE,
    .pid= 0x0BD0,
    .name = "PCIe-IDI-24",
    .isr = interrupt_pcie_style_6,
    .init = NULL,
    .enable = enable_pcie_style_6,
    .disable = disable_pcie_style_6,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0BD1, .Model = "PCIe-IDI-24B", .IRQ = &NYI,
    .pid= 0x0BD1,
    .name = "PCIe-IDI-24B",
    .isr = NULL,
    .init = NULL,
    .enable = NULL,
    .disable = NULL,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0C40, .Model = "PCIe-DIO-144", .IRQ = &PCIE_1_STYLE,
    .pid= 0x0C40,
    .name = "PCIe-DIO-144",
    .isr = interrupt_pcie_style_1,
    .init = NULL,
    .enable = enable_pcie_style_1,
    .disable = disable_pcie_style_1,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0C50, .Model = "PCI-DIO-24H", .IRQ = &PCI_10_STYLE,
    .pid= 0x0C50,
    .name = "PCI-DIO-24H",
    .isr = interrupt_pci_style_10,
    .init = NULL,
    .enable = enable_pci_style_10,
    .disable = disable_pci_style_10,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0C51, .Model = "PCI-DIO-24D", .IRQ = &PCI_10_STYLE,
    .pid= 0x0C51,
    .name = "PCI-DIO-24D",
    .isr = interrupt_pci_style_10,
    .init = NULL,
    .enable = enable_pci_style_10,
    .disable = disable_pci_style_10,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0C52, .Model = "PCIe-DIO-24", .IRQ = &PCIE_7_STYLE,
    .pid= 0x0C52,
    .name = "PCIe-DIO-24",
    .isr = interrupt_pcie_style_7,
    .init = NULL,
    .enable = enable_pcie_style_7,
    .disable = disable_pcie_style_7,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0C53, .Model = "PCIe-DIO-24D/H", .IRQ = &PCIE_7_STYLE,
    .pid= 0x0C53,
    .name = "PCIe-DIO-24D/H",
    .isr = interrupt_pcie_style_7,
    .init = NULL,
    .enable = enable_pcie_style_7,
    .disable = disable_pcie_style_7,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0C54, .Model = "PCIe-DIO-24HC", .IRQ = &PCIE_4_STYLE,
    .pid= 0x0C54,
    .name = "PCIe-DIO-24HC",
    .isr = interrupt_pcie_style_4,
    .init = NULL,
    .enable = enable_pcie_style_4,
    .disable = disable_pcie_style_4,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0C57, .Model = "mPCIe-DIO-24", .IRQ = &PCIE_4_STYLE,
    .pid= 0x0C57,
    .name = "mPCIe-DIO-24",
    .isr = interrupt_pcie_style_4,
    .init = NULL,
    .enable = enable_pcie_style_4,
    .disable = disable_pcie_style_4,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0C60, .Model = "PCI-DIO-48(H)", .IRQ = &PCI_8_STYLE,
    .pid= 0x0C60,
    .name = "PCI-DIO-48(H)",
    .isr = interrupt_pci_style_8,
    .init = NULL,
    .enable = enable_pci_style_8,
    .disable = disable_pci_style_8,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0C61, .Model = "PCIe-DIO-48", .IRQ = &PCIE_4_STYLE,
    .pid= 0x0C61,
    .name = "PCIe-DIO-48",
    .isr = interrupt_pcie_style_4,
    .init = NULL,
    .enable = enable_pcie_style_4,
    .disable = disable_pcie_style_4,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0C62, .Model = "P104-DIO-48", .IRQ = &PCI_NO_IRQ_STYLE,
    .pid= 0x0C62,
    .name = "P104-DIO-48",
    .isr = NULL,
    .init = NULL,
    .enable = NULL,
    .disable = NULL,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0C68, .Model = "PCI-DIO-72", .IRQ = &PCI_2_STYLE,
    .pid= 0x0C68,
    .name = "PCI-DIO-72",
    .isr = interrupt_pci_style_2,
    .init = NULL,
    .enable = enable_pci_style_2,
    .disable = disable_pci_style_2,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0C69, .Model = "P104-DIO-96", .IRQ = &PCI_NO_IRQ_STYLE,
    .pid= 0x0C69,
    .name = "P104-DIO-96",
    .isr = NULL,
    .init = NULL,
    .enable = NULL,
    .disable = NULL,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0C6A, .Model = "PCIe-DIO-72", .IRQ = &PCIE_1_STYLE,
    .pid= 0x0C6A,
    .name = "PCIe-DIO-72",
    .isr = interrupt_pcie_style_1,
    .init = NULL,
    .enable = enable_pcie_style_1,
    .disable = disable_pcie_style_1,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0C70, .Model = "PCI-DIO-96", .IRQ = &PCI_2_STYLE,
    .pid= 0x0C70,
    .name = "PCI-DIO-96",
    .isr = interrupt_pci_style_2,
    .init = NULL,
    .enable = enable_pci_style_2,
    .disable = disable_pci_style_2,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0C71, .Model = "PCIe-DIO-96", .IRQ = &PCIE_1_STYLE,
    .pid= 0x0C71,
    .name = "PCIe-DIO-96",
    .isr = interrupt_pcie_style_1,
    .init = NULL,
    .enable = enable_pcie_style_1,
    .disable = disable_pcie_style_1,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0C78, .Model = "PCI-DIO-120", .IRQ = &PCI_2_STYLE,
    .pid= 0x0C78,
    .name = "PCI-DIO-120",
    .isr = interrupt_pci_style_2,
    .init = NULL,
    .enable = enable_pci_style_2,
    .disable = disable_pci_style_2,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0C79, .Model = "PCIe-DIO-120", .IRQ = &PCIE_1_STYLE,
    .pid= 0x0C79,
    .name = "PCIe-DIO-120",
    .isr = interrupt_pcie_style_1,
    .init = NULL,
    .enable = enable_pcie_style_1,
    .disable = disable_pcie_style_1,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0DC8, .Model = "PCI-IDIO-16", .IRQ = &PCI_3_STYLE,
    .pid= 0x0DC8,
    .name = "PCI-IDIO-16",
    .isr = interrupt_pci_style_3,
    .init = NULL,
    .enable = enable_pci_style_3,
    .disable = disable_pci_style_3,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0E50, .Model = "PCI-DIO-24S", .IRQ = &PCI_8_STYLE,
    .pid= 0x0E50,
    .name = "PCI-DIO-24S",
    .isr = interrupt_pci_style_8,
    .init = NULL,
    .enable = enable_pci_style_8,
    .disable = disable_pci_style_8,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0E51, .Model = "PCI-DIO-24H(C)", .IRQ = &PCI_10_STYLE,
    .pid= 0x0E51,
    .name = "PCI-DIO-24H(C)",
    .isr = interrupt_pci_style_10,
    .init = NULL,
    .enable = enable_pci_style_10,
    .disable = disable_pci_style_10,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0E52, .Model = "PCI-DIO-24D(C)", .IRQ = &PCI_10_STYLE,
    .pid= 0x0E52,
    .name = "PCI-DIO-24D(C)",
    .isr = interrupt_pci_style_10,
    .init = NULL,
    .enable = enable_pci_style_10,
    .disable = disable_pci_style_10,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0E53, .Model = "PCIe-DIO-24S", .IRQ = &PCIE_4_STYLE,
    .pid= 0x0E53,
    .name = "PCIe-DIO-24S",
    .isr = interrupt_pcie_style_4,
    .init = NULL,
    .enable = enable_pcie_style_4,
    .disable = disable_pcie_style_4,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0E54, .Model = "PCIe-DIO-24DS/HS", .IRQ = &PCIE_4_STYLE,
    .pid= 0x0E54,
    .name = "PCIe-DIO-24DS/HS",
    .isr = interrupt_pcie_style_4,
    .init = NULL,
    .enable = enable_pcie_style_4,
    .disable = disable_pcie_style_4,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0E55, .Model = "PCIe-DIO-24DC", .IRQ = &PCIE_7_STYLE,
    .pid= 0x0E55,
    .name = "PCIe-DIO-24DC",
    .isr = interrupt_pcie_style_7,
    .init = NULL,
    .enable = enable_pcie_style_7,
    .disable = disable_pcie_style_7,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0E56, .Model = "PCIe-DIO-24DCS", .IRQ = &PCIE_4_STYLE,
    .pid= 0x0E56,
    .name = "PCIe-DIO-24DCS",
    .isr = interrupt_pcie_style_4,
    .init = NULL,
    .enable = enable_pcie_style_4,
    .disable = disable_pcie_style_4,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0E57, .Model = "PCI-DIO-48HS", .IRQ = &PCIE_4_STYLE,
    .pid= 0x0E57,
    .name = "PCI-DIO-48HS",
    .isr = interrupt_pcie_style_4,
    .init = NULL,
    .enable = enable_pcie_style_4,
    .disable = disable_pcie_style_4,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0E60, .Model = "PCI-DIO-48S", .IRQ = &PCI_8_STYLE,
    .pid= 0x0E60,
    .name = "PCI-DIO-48S",
    .isr = interrupt_pci_style_8,
    .init = NULL,
    .enable = enable_pci_style_8,
    .disable = disable_pci_style_8,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0E61, .Model = "PCIe-DIO-48S", .IRQ = &PCIE_4_STYLE,
    .pid= 0x0E61,
    .name = "PCIe-DIO-48S",
    .isr = interrupt_pcie_style_4,
    .init = NULL,
    .enable = enable_pcie_style_4,
    .disable = disable_pcie_style_4,
    .clear = NULL,
  },
  {//TODO: Find PCI_11_STYLE operations. Was NYI in previous table
    //.pciDevId = 0x0E62, .Model = "P104-DIO-48S", .IRQ = &PCI_11_STYLE,
    .pid= 0x0E62,
    .name = "P104-DIO-48S",
    .isr = NULL,
    .init = NULL,
    .enable = NULL,
    .disable = NULL,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0E63, .Model = "PCIe-EZ-BLEND", .IRQ = &NYI,
    .pid= 0x0E63,
    .name = "PCIe-EZ-BLEND",
    .isr = NULL,
    .init = NULL,
    .enable = NULL,
    .disable = NULL,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0E6A, .Model = "PCIe-DIO-72S", .IRQ = &PCIE_1_STYLE,
    .pid= 0x0E6A,
    .name = "PCIe-DIO-72S",
    .isr = interrupt_pcie_style_1,
    .init = NULL,
    .enable = enable_pcie_style_1,
    .disable = disable_pcie_style_1,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0E71, .Model = "PCIe-DIO-96S", .IRQ = &PCIE_1_STYLE,
    .pid= 0x0E71,
    .name = "PCIe-DIO-96S",
    .isr = interrupt_pcie_style_1,
    .init = NULL,
    .enable = enable_pcie_style_1,
    .disable = disable_pcie_style_1,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0E79, .Model = "PCIe-DIO-120S", .IRQ = &PCIE_1_STYLE,
    .pid= 0x0E79,
    .name = "PCIe-DIO-120S",
    .isr = interrupt_pcie_style_1,
    .init = NULL,
    .enable = enable_pcie_style_1,
    .disable = disable_pcie_style_1,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0F00, .Model = "PCI-IIRO-8", .IRQ = &PCI_3_STYLE,
    .pid= 0x0F00,
    .name = "PCI-IIRO-8",
    .isr = interrupt_pci_style_3,
    .init = NULL,
    .enable = enable_pci_style_3,
    .disable = disable_pci_style_3,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0F01, .Model = "LPCI-IIRO-8", .IRQ = &PCI_3_STYLE,
    .pid= 0x0F01,
    .name = "LPCI-IIRO-8",
    .isr = interrupt_pci_style_3,
    .init = NULL,
    .enable = enable_pci_style_3,
    .disable = disable_pci_style_3,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0F02, .Model = "PCIe-IIRO-8", .IRQ = &PCIE_3_STYLE,
    .pid= 0x0F02,
    .name = "PCIe-IIRO-8",
    .isr = interrupt_pcie_style_3,
    .init = NULL,
    .enable = enable_pcie_style_3,
    .disable = disable_pcie_style_3,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0F08, .Model = "PCI-IIRO-16", .IRQ = &PCI_3_STYLE,
    .pid= 0x0F08,
    .name = "PCI-IIRO-16",
    .isr = interrupt_pci_style_3,
    .init = NULL,
    .enable = enable_pci_style_3,
    .disable = disable_pci_style_3,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0F09, .Model = "PCIe-IIRO-16", .IRQ = &PCIE_3_STYLE,
    .pid= 0x0F09,
    .name = "PCIe-IIRO-16",
    .isr = interrupt_pcie_style_3,
    .init = NULL,
    .enable = enable_pcie_style_3,
    .disable = disable_pcie_style_3,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0FC0, .Model = "PCIe-IDIO-12", .IRQ = &PCIE_6_STYLE,
    .pid= 0x0FC0,
    .name = "PCIe-IDIO-12",
    .isr = interrupt_pcie_style_6,
    .init = NULL,
    .enable = enable_pcie_style_6,
    .disable = disable_pcie_style_6,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0FC1, .Model = "PCIe-IDI-12", .IRQ = &PCIE_6_STYLE,
    .pid= 0x0FC1,
    .name = "PCIe-IDI-12",
    .isr = interrupt_pcie_style_6,
    .init = NULL,
    .enable = enable_pcie_style_6,
    .disable = disable_pcie_style_6,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0FC2, .Model = "PCIe-IDO-12", .IRQ = &PCIE_6_STYLE,
    .pid= 0x0FC2,
    .name = "PCIe-IDO-12",
    .isr = interrupt_pcie_style_6,
    .init = NULL,
    .enable = enable_pcie_style_6,
    .disable = disable_pcie_style_6,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0FD0, .Model = "PCIe-IDIO-24", .IRQ = &PCIE_6_STYLE,
    .pid= 0x0FD0,
    .name = "PCIe-IDIO-24",
    .isr = interrupt_pcie_style_6,
    .init = NULL,
    .enable = enable_pcie_style_6,
    .disable = disable_pcie_style_6,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x0FD1, .Model = "PCIe-IDIO-24B", .IRQ = &NYI,
    .pid= 0x0FD1,
    .name = "PCIe-IDIO-24B",
    .isr = NULL,
    .init = NULL,
    .enable = NULL,
    .disable = NULL,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x2230, .Model = "PCI-QUAD-8", .IRQ = &PCI_13_STYLE,
    .pid= 0x2230,
    .name = "PCI-QUAD-8",
    .isr = interrupt_pci_style_13,
    .init = NULL,
    .enable = enable_pci_style_13,
    .disable = disable_pci_style_13,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x2231, .Model = "PCI-QUAD-4", .IRQ = &PCI_13_STYLE,
    .pid= 0x2231,
    .name = "PCI-QUAD-4",
    .isr = interrupt_pci_style_13,
    .init = NULL,
    .enable = enable_pci_style_13,
    .disable = disable_pci_style_13,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x22C0, .Model = "PCI-WDG-CSM", .IRQ = &PCI_7_STYLE,
    .pid= 0x22C0,
    .name = "PCI-WDG-CSM",
    .isr = interrupt_pci_style_7,
    .init = NULL,
    .enable = enable_pci_style_7,
    .disable = disable_pci_style_7,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x25C0, .Model = "P104-WDG-E", .IRQ = &PCI_6_STYLE,
    .pid= 0x25C0,
    .name = "P104-WDG-E",
    .isr = interrupt_pci_style_6,
    .init = NULL,
    .enable = enable_pci_style_6,
    .disable = disable_pci_style_6,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x2C50, .Model = "PCI-DIO-96CT", .IRQ = &PCI_2_STYLE,
    .pid= 0x2C50,
    .name = "PCI-DIO-96CT",
    .isr = interrupt_pci_style_2,
    .init = NULL,
    .enable = enable_pci_style_2,
    .disable = disable_pci_style_2,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x2C58, .Model = "PCI-DIO-96C3", .IRQ = &PCI_2_STYLE,
    .pid= 0x2C58,
    .name = "PCI-DIO-96C3",
    .isr = interrupt_pci_style_2,
    .init = NULL,
    .enable = enable_pci_style_2,
    .disable = disable_pci_style_2,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x2C59, .Model = "PCIe-DIO-96C3", .IRQ = &PCIE_1_STYLE,
    .pid= 0x2C59,
    .name = "PCIe-DIO-96C3",
    .isr = interrupt_pcie_style_1,
    .init = NULL,
    .enable = enable_pcie_style_1,
    .disable = disable_pcie_style_1,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x2C70, .Model = "PCI-DIO-96CT", .IRQ = &NYI,
    .pid= 0x2C70,
    .name = "PCI-DIO-96CT",
    .isr = NULL,
    .init = NULL,
    .enable = NULL,
    .disable = NULL,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x2E50, .Model = "mPCIe-DIO-24A", .IRQ = &PCIE_4_STYLE,
    .pid= 0x2E50,
    .name = "mPCIe-DIO-24A",
    .isr = interrupt_pcie_style_4,
    .init = NULL,
    .enable = enable_pcie_style_4,
    .disable = disable_pcie_style_4,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x2EE0, .Model = "PCIe-DIO24S-CTR12", .IRQ = &PCIE_5_STYLE,
    .pid= 0x2EE0,
    .name = "PCIe-DIO24S-CTR12",
    .isr = interrupt_pcie_style_5,
    .init = NULL,
    .enable = enable_pcie_style_5,
    .disable = disable_pcie_style_5,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x2FC0, .Model = "P104-WDG-CSM", .IRQ = &PCI_6_STYLE,
    .pid= 0x2FC0,
    .name = "P104-WDG-CSM",
    .isr = interrupt_pci_style_6,
    .init = NULL,
    .enable = enable_pci_style_6,
    .disable = disable_pci_style_6,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x2FC1, .Model = "P104-WDG-CSMA", .IRQ = &PCI_6_STYLE,
    .pid= 0x2FC1,
    .name = "P104-WDG-CSMA",
    .isr = interrupt_pci_style_6,
    .init = NULL,
    .enable = enable_pci_style_6,
    .disable = disable_pci_style_6,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x4890, .Model = "PCIe-DA12-2", .IRQ = &PCIE_8_STYLE,
    .pid= 0x4890,
    .name = "PCIe-DA12-2",
    .isr = interrupt_pcie_style_8,
    .init = NULL,
    .enable = enable_pcie_style_8,
    .disable = disable_pcie_style_8,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x4898, .Model = "PCIe-DA12-4", .IRQ = &PCIE_8_STYLE,
    .pid= 0x4898,
    .name = "PCIe-DA12-4",
    .isr = interrupt_pcie_style_8,
    .init = NULL,
    .enable = enable_pcie_style_8,
    .disable = disable_pcie_style_8,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x48a0, .Model = "PCIe-DA12-6", .IRQ = &PCIE_8_STYLE,
    .pid= 0x48a0,
    .name = "PCIe-DA12-6",
    .isr = interrupt_pcie_style_8,
    .init = NULL,
    .enable = enable_pcie_style_8,
    .disable = disable_pcie_style_8,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x48a8, .Model = "PCIe-DA12-8", .IRQ = &PCIE_8_STYLE,
    .pid= 0x48a8,
    .name = "PCIe-DA12-8",
    .isr = interrupt_pcie_style_8,
    .init = NULL,
    .enable = enable_pcie_style_8,
    .disable = disable_pcie_style_8,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x48b0, .Model = "PCIe-DA12-16", .IRQ = &PCIE_8_STYLE,
    .pid= 0x48b0,
    .name = "PCIe-DA12-16",
    .isr = interrupt_pcie_style_8,
    .init = NULL,
    .enable = enable_pcie_style_8,
    .disable = disable_pcie_style_8,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x48d0, .Model = "PCIe-DA16-2", .IRQ = &PCIE_8_STYLE,
    .pid= 0x48d0,
    .name = "PCIe-DA16-2",
    .isr = interrupt_pcie_style_8,
    .init = NULL,
    .enable = enable_pcie_style_8,
    .disable = disable_pcie_style_8,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x48d8, .Model = "PCIe-DA16-4", .IRQ = &PCIE_8_STYLE,
    .pid= 0x48d8,
    .name = "PCIe-DA16-4",
    .isr = interrupt_pcie_style_8,
    .init = NULL,
    .enable = enable_pcie_style_8,
    .disable = disable_pcie_style_8,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x48e0, .Model = "PCIe-DA16-6", .IRQ = &PCIE_8_STYLE,
    .pid= 0x48e0,
    .name = "PCIe-DA16-6",
    .isr = interrupt_pcie_style_8,
    .init = NULL,
    .enable = enable_pcie_style_8,
    .disable = disable_pcie_style_8,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x48e8, .Model = "PCIe-DA16-8", .IRQ = &PCIE_8_STYLE,
    .pid= 0x48e8,
    .name = "PCIe-DA16-8",
    .isr = interrupt_pcie_style_8,
    .init = NULL,
    .enable = enable_pcie_style_8,
    .disable = disable_pcie_style_8,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x48f0, .Model = "PCIe-DA16-16", .IRQ = &PCIE_8_STYLE,
    .pid= 0x48f0,
    .name = "PCIe-DA16-16",
    .isr = interrupt_pcie_style_8,
    .init = NULL,
    .enable = enable_pcie_style_8,
    .disable = disable_pcie_style_8,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x5ED0, .Model = "PCI-DAC", .IRQ = &NYI,
    .pid= 0x5ED0,
    .name = "PCI-DAC",
    .isr = NULL,
    .init = NULL,
    .enable = NULL,
    .disable = NULL,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x6C90, .Model = "PCI-DA12-2", .IRQ = &PCI_4_STYLE,
    .pid= 0x6C90,
    .name = "PCI-DA12-2",
    .isr = interrupt_pci_style_4,
    .init = NULL,
    .enable = enable_pci_style_4,
    .disable = disable_pci_style_4,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x6C98, .Model = "PCI-DA12-4", .IRQ = &PCI_4_STYLE,
    .pid= 0x6C98,
    .name = "PCI-DA12-4",
    .isr = interrupt_pci_style_4,
    .init = NULL,
    .enable = enable_pci_style_4,
    .disable = disable_pci_style_4,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x6CA0, .Model = "PCI-DA12-6", .IRQ = &PCI_4_STYLE,
    .pid= 0x6CA0,
    .name = "PCI-DA12-6",
    .isr = interrupt_pci_style_4,
    .init = NULL,
    .enable = enable_pci_style_4,
    .disable = disable_pci_style_4,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x6CA8, .Model = "PCI-DA12-8", .IRQ = &PCI_4_STYLE,
    .pid= 0x6CA8,
    .name = "PCI-DA12-8",
    .isr = interrupt_pci_style_4,
    .init = NULL,
    .enable = enable_pci_style_4,
    .disable = disable_pci_style_4,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x6CA9, .Model = "PCI-DA12-8V", .IRQ = &PCI_4_STYLE,
    .pid= 0x6CA9,
    .name = "PCI-DA12-8V",
    .isr = interrupt_pci_style_4,
    .init = NULL,
    .enable = enable_pci_style_4,
    .disable = disable_pci_style_4,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x6CB0, .Model = "PCI-DA12-16", .IRQ = &PCI_4_STYLE,
    .pid= 0x6CB0,
    .name = "PCI-DA12-16",
    .isr = interrupt_pci_style_4,
    .init = NULL,
    .enable = enable_pci_style_4,
    .disable = disable_pci_style_4,
    .clear = NULL,
  },
  {
    //.pciDevId = 0x6CB1, .Model = "PCI-DA12-16V", .IRQ = &PCI_4_STYLE,
    .pid= 0x6CB1,
    .name = "PCI-DA12-16V",
    .isr = interrupt_pci_style_4,
    .init = NULL,
    .enable = enable_pci_style_4,
    .disable = disable_pci_style_4,
    .clear = NULL,
  },
  {
    //.pciDevId = 0xACA8, .Model = "PCI-AI12-16", .IRQ = &PCI_12_STYLE,
    .pid= 0xACA8,
    .name = "PCI-AI12-16",
    .isr = interrupt_pci_style_12,
    .init = NULL,
    .enable = enable_pci_style_12,
    .disable = disable_pci_style_12,
    .clear = NULL,
  },
  {
    //.pciDevId = 0xACA9, .Model = "PCI-AI12-16A", .IRQ = &PCI_12_STYLE,
    .pid= 0xACA9,
    .name = "PCI-AI12-16A",
    .isr = interrupt_pci_style_12,
    .init = NULL,
    .enable = enable_pci_style_12,
    .disable = disable_pci_style_12,
    .clear = NULL,
  },
  {
    //.pciDevId = 0xECA8, .Model = "PCI-AIO12-16", .IRQ = &PCI_12_STYLE,
    .pid= 0xECA8,
    .name = "PCI-AIO12-16",
    .isr = interrupt_pci_style_12,
    .init = NULL,
    .enable = enable_pci_style_12,
    .disable = disable_pci_style_12,
    .clear = NULL,
  },
  {
    //.pciDevId = 0xECA9, .Model = "PCI-A12-16", .IRQ = &PCI_12_STYLE,
    .pid= 0xECA9,
    .name = "PCI-A12-16",
    .isr = interrupt_pci_style_12,
    .init = NULL,
    .enable = enable_pci_style_12,
    .disable = disable_pci_style_12,
    .clear = NULL,
  },
  {
    //.pciDevId = 0xECAA, .Model = "PCI-A12-16A", .IRQ = &PCI_12_STYLE,
    .pid= 0xECAA,
    .name = "PCI-A12-16A",
    .isr = interrupt_pci_style_12,
    .init = NULL,
    .enable = enable_pci_style_12,
    .disable = disable_pci_style_12,
    .clear = NULL,
  },
  {
    //.pciDevId = 0xECE8, .Model = "LPCI-A16-16A", .IRQ = &PCI_9_STYLE,
    .pid= 0xECE8,
    .name = "LPCI-A16-16A",
    .isr = interrupt_pci_style_9,
    .init = NULL,
    .enable = enable_pci_style_9,
    .disable = disable_pci_style_9,
    .clear = NULL,
  },
  {
    //.pciDevId = 0xECE9, .Model = "LPCI-AIO16A", .IRQ = &PCI_1_STYLE,
    .pid= 0xECE9,
    .name = "LPCI-AIO16A",
    .isr = interrupt_pci_style_1,
    .init = NULL,
    .enable = enable_pci_style_1,
    .disable = disable_pci_style_1,
    .clear = NULL,
  },
  //Everything from this point forward didn't exist in the old driver.
  //When adding new enries try to reuse previously defined styles.
  //If none fit then use function names that are different format
  {
    .pid = 0xC2EF,
    .name = "PCIe-ADIO16-16FDS",
    .isr = interrupt_adio16f_style,
    .init = NULL,
    .enable = enable_adio16f_style,
    .disable = disable_adio16f_style,
    .clear = NULL,
    .has_dma = true,
  },
  {
    .pid = 0xC2EC,
    .name = "PCIe-ADIO16-16F",
    .isr = interrupt_adio16f_style,
    .init = NULL,
    .enable = enable_adio16f_style,
    .disable = disable_adio16f_style,
    .clear = NULL,
    .has_dma = true,
  },
  {
    .pid = 0xC2ED,
    .name = "PCIe-ADIO16-16A",
    .isr = interrupt_adio16f_style,
    .init = NULL,
    .enable = enable_adio16f_style,
    .disable = disable_adio16f_style,
    .clear = NULL,
    .has_dma = true,
  },
  {
    .pid = 0xC2EE,
    .name = "PCIe-ADIO16-16E",
    .isr = interrupt_adio16f_style,
    .init = NULL,
    .enable = enable_adio16f_style,
    .disable = disable_adio16f_style,
    .clear = NULL,
    .has_dma = true,
  },
  {
    .pid = 0x82EC,
    .name = "PCIe-ADI16-16F",
    .isr = interrupt_adio16f_style,
    .init = NULL,
    .enable = enable_adio16f_style,
    .disable = disable_adio16f_style,
    .clear = NULL,
    .has_dma = true,
  },
  {
    .pid = 0x82ED,
    .name = "PCIe-ADI16-16A",
    .isr = interrupt_adio16f_style,
    .init = NULL,
    .enable = enable_adio16f_style,
    .disable = disable_adio16f_style,
    .clear = NULL,
    .has_dma = true,
  },
  {
    .pid = 0x82EE,
    .name = "PCIe-ADI16-16E",
    .isr = interrupt_adio16f_style,
    .init = NULL,
    .enable = enable_adio16f_style,
    .disable = disable_adio16f_style,
    .clear = NULL,
    .has_dma = true,
  },
  {
    .pid = 0xC25C,
    .name = "PCIe-ADIO12-16A",
    .isr = interrupt_adio16f_style,
    .init = NULL,
    .enable = enable_adio16f_style,
    .disable = disable_adio16f_style,
    .clear = NULL,
    .has_dma = true,
  },
  {
    .pid = 0xC25D,
    .name = "PCIe-ADIO12-16",
    .isr = interrupt_adio16f_style,
    .init = NULL,
    .enable = enable_adio16f_style,
    .disable = disable_adio16f_style,
    .clear = NULL,
    .has_dma = true,
  },
  {
    .pid = 0xC25E,
    .name = "PCIe-ADIO12-16E",
    .isr = interrupt_adio16f_style,
    .init = NULL,
    .enable = enable_adio16f_style,
    .disable = disable_adio16f_style,
    .clear = NULL,
    .has_dma = true,
  },
  {
    .pid = 0x825C,
    .name = "PCIe-ADI12-16A",
    .isr = interrupt_adio16f_style,
    .init = NULL,
    .enable = enable_adio16f_style,
    .disable = disable_adio16f_style,
    .clear = NULL,
    .has_dma = true,
  },
  {
    .pid = 0x825D,
    .name = "PCIe-ADI12-16F",
    .isr = interrupt_adio16f_style,
    .init = NULL,
    .enable = enable_adio16f_style,
    .disable = disable_adio16f_style,
    .clear = NULL,
    .has_dma = true,
  },
  {
    .pid = 0x825E,
    .name = "PCIe-ADI12-16F",
    .isr = interrupt_adio16f_style,
    .init = NULL,
    .enable = enable_adio16f_style,
    .disable = disable_adio16f_style,
    .clear = NULL,
    .has_dma = true,
  },
};

#define NUM_ACCES_PCI_DEVICES sizeof(accesio_pci_device_descriptors)/sizeof(accesio_pci_device_descriptors[0])

#ifdef __KERNEL__
static struct pci_device_id acces_pci_id_table[] =
 {
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0100) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0101) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0102) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0103) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0104) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0105) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0106) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0107) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0108) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0109) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x010a) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x010b) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x010c) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x010d) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x010e) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x010f) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0508) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0518) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0520) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0521) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0703) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x07c0) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x07d0) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0920) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0bc0) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0bc1) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0bd0) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0bd1) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0c40) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0c50) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0c51) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0c52) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0c53) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0c54) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0c57) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0c60) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0c61) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0c62) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0c68) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0c69) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0c6a) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0c70) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0c71) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0c78) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0c79) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0dc8) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0e50) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0e51) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0e52) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0e53) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0e54) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0e55) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0e56) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0e57) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0e60) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0e61) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0e62) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0e63) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0e6a) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0e71) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0e79) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0f00) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0f01) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0f02) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0f08) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0f09) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0fc0) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0fc1) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0fc2) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0fd0) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x0fd1) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x2230) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x2231) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x22c0) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x25c0) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x2c50) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x2c58) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x2c59) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x2c70) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x2e50) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x2ee0) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x2fc0) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x2fc1) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x4890) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x4898) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x48a0) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x48a8) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x48b0) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x48d0) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x48d8) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x48e0) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x48e8) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x48f0) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x5ed0) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x6c90) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x6c98) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x6ca0) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x6ca8) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x6ca9) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x6cb0) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x6cb1) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0xaca8) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0xaca9) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0xeca8) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0xeca9) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0xecaa) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0xece8) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0xece9) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0xc2ef) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0xc2ec) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0xc2ed) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0xc2ee) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x82ec) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x82ed) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x82ee) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0xc25c) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0xc25d) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0xc25e) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x825c) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x825d) },
{ PCI_DEVICE(ACCES_PCI_VEN_ID, 0x825e) },
{0},
 };
 #endif